# COGS 108 - Data Checkpoint

## Authors

<!-- Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft -->

* Minnie Zhang: Conceptualization, Writing - Review & Editing
* Theresa Doan: Conceptualization, Data Wrangling
* Bryan Nguyen: Conceptualization, Writing - Review & Editing,
* Michael Kroyan: Conceptualization, Writing - Review & Editing, Data Wrangling
* Janice Rincon: Conceptualization, Writing - Review & Editing

## Research Question

 <!-- **Feedback:** You can include more information on what models you will use to predict the quality of the wine and what exact metric are you using to predict the quality of wine? -->

 What is the relationship between the physical and chemical characteristics of wine (acidity, chlorides, pH, sulphates, alcohol, etc.) and wine quality ratings?
 Using machine learning models, such as Linear Regression and Random Forest, can we predict the quality of quality score (0-10) of an unseen wine sample, and how accurately can this prediction be measured using metrics such as RMSE and $R^2$?

## Background and Prior Work

<!-- **Feedback:** This is a decent background, but to make this better you can include more information on how the outcome of these studies influence the direction of the project and what your project does that goes beyond / different than what has already been done -->

Wine tasting has traditionally been an exclusive and highly specialized activity, requiring professional recognition that is done through formal training the completion of a sommelier exam. Evaluating wine quality involves numerous sensory factors, including texture, odor, flavor, color, and touch, all of which contribute to the overall perception of quality.<a name="cite_ref-1"></a><sup>1</sup> Traditionally, wine quality has been assessed subjectively through the human palette, where individual preferences and sensory perceptions dictate the quality. The human palette though, while fully capable of capturing the quality of wine, is a variable and in many ways subjective during the process. Therefore, objective methods have known to be used as well; for example, NIR spectroscopy(Near Infrared Spectroscopy) is used in evaluating certain compounds in flavor in the wine.<a name="cite_ref-1"></a><sup>2</sup>

This raises the question of whether we can understand more about how wine qualities are determined through studying its components. Specifically, how certain chemical components may influence the wine's taste or texture, and if whether these findings could help us predict a wine's quality given its statistics.

A similar study was conducted with two wine quality datasets, for red and white wine respectively. The study applied multiple regression to predict continuous quality scores, regression trees to capture nonlinear relationships, and classification models to group wines based on these properties. <a name="cite_ref-2"></a><sup>3</sup> They concluded that wine quality does not seem to have any major correlation with the chemical properties.

One prior study focused specifically on predicting red wine quality using physical and chemical properties like acidity, pH, alcohol content, etc. This work applied linear models and mulitnomial logistic regression to predict discrete quality ratings, demonstrating that objective wine characteristics can explain a decent portion of the variation and perceived quality in wine. Their results suggeste that seemingly simple statistical models can capture meaningful relationships between wine traits and quality.

Another study expanded on this idea except took a different approach in applying machine learning methods to identify which wine attributes and traits are most influential in determining overall quality. Rather than focusing on prediction alone, they emphasized feature importance, highlighting which chemical parameters contribute most to assessing quality. They found that certain variables like alcohol content and volatile acidity played a major role more times than not in predicting wine quality, which emphasized the idea that not all features contribute equally to the quality score.

Taking away from the studies, we aim to extend upon prior studies' results by investigating not only the features, but also whether certain combinations of chemical components may have a larger impact on the wine quality; specifically, if the  interactions within the features themselves could produce different results than just analyzing them one by one. While previous works determine that majority of the features do not contribute to the wine quality, by comparing models that study only individual predictors with models that have them interact, we hope to find whether accounting for these relationships improves predictive performance and would provide us a more comprehensive understanding of what are the contributing factors for wine quality.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Reynolds AG. Managing Wine Quality. Vol. 1, Viticulture and Wine Quality. Woodhead Pub. ; Boca Raton; 2010.

2. <a name="cite_note-2"></a> [^](#cite_ref-2) Analysis of wine quality Data | STAT 897D. https://online.stat.psu.edu/stat857/node/223/

3. <a name="cite_note-2"></a> [^](#cite_ref-3) Meng, X. Statistical Paradises and Paradoxes in Big Data (I): Law of Large Populations, Big Data Paradox, and the 2016 US Presidential Election. North Carolina State University, ST 540 Lecture Notes, 2019. https://st540.wordpress.ncsu.edu/files/2019/05/Meng.pdf

4. <a name="cite_note-2"></a> [^](#cite_ref-4) Li, Y.; Wu, J.; Liu, Z. Quality Prediction of Wine Based on Machine Learning. Journal of Food and Nutrition Research, Vol. 9, No. 3, Scientific Research Publishing (SCIRP), 2021. https://www.scirp.org/journal/paperinformation?paperid=107796

## Hypothesis

We predict that wine quality is strongly determined by the combinations of the wine's properties rather than the properties on their own. As mentioned before, prior work has shown that the standalone properties such as alcohol content, acidity, etc. on their own tend to have strong influences with quality, while others do not. This suggests that wine quality can be deduced by a combination or balance between components rather than the significance of a feature on its own. We will examine this by exploring how combinations, such as sweetness/acidity, interact to influence the wine quality collectively. We believe that combinations such as sweetness/acidity in relation to other combinations such as sulfur/alcohol content or any other sulfur related combinations will be more predictive and decisive in terms of wine quality. The wine quality will be assessed with the dataset's already included quality score, with the traits of the wine (sugar, acidity), serving as independent variables as we explore whether modeling with interaction in mind among features will explain variation better than models which treat features separately.

## Data

### Vihno Verde Wine Quality
<!--
Instructions:
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it" -->

* Dataset Name:  Wine Quality
* Link to the dataset: https://archive.ics.uci.edu/dataset/186/wine+quality
* Number of observations: 6497
* Number of variables: 12
* Input Variables (based on physicochemical tests):
  *   `fixed_acidity` (g(tartaric acid)/liter): Amount of non-volatile acids (e.g., tartaric acid, malic acit, etc.) in the wine. Contributes to the wine's overall acidity and taste.
  *   `volatile_acidity` (g(acetic acid)/liter): Amount of volatile acids, mainly acetic acid. High levels can cause an unpleasant vinegar-like taste.
  *   `citric_acid` (g/liter): Concentration of citric acid in the wine. It can add freshness and flavor, though it is usually present in small amounts.
  *   `residual_sugar`(g/liter): Amount of sugar remaining after fermentation stops. Higher values indicate sweeter wine.
  *   `chlorides` (g(sodium chloride)/liter): Amount of sodium chloride (salt) in the wine. High levels may negatively affect taste.
  *   `free_sulfur_dioxide` (mg/liter): Amount of unbound sulfur dioxide ($SO_2$) in the wine. It helps prevent microbial growth and oxidation.
  *   `total_sulfur_dioxide` (mg/liter): Total amount of sulfur dioxide ($SO_2$), including both free and bound. High levels can affect taste and aroma.
  *   `density` (g/cm³): Density of the wine. It is influenced by alcohol and sugar content.
  *   `pH`: Measure of acidity/alkalinity of the wine. Lower pH indicates higher acidity.
  *   `sulphates` (g(potassium sulphate)/liter): Amount of potassium sulphate. It contributes to microbial stability and may enhance flavor.
  *   `alcohol` (vol.%): Percentage of alcohol content in the wine. It strongly influences body and perception of quality.
* Output Variable (based on sensory data):
  *   `quality`: Sensory quality score, ranging from 0 (very bad) to 10 (excellent).


* The dataset is composed of red and white variants of the Portugese "Vinho Verde" wine only and does not include information of any other type/style of wine. This raises a concern of generalizability as our findings cannot be extended and applied to other types and regions of wine. In addition, the data set is imbalanced with red wine variants having more observations (#) than red wine variants. (Elaborate) Lastly, per UCI's website, the `quality` output variable is not balanced with the majority of wines being classified as "normal" and only small number of observations being classified as "low" or "excellent". This, again, may be a concern for generalizability as the dataset may not include enough observations for each class for the model to learn meaningful relationships.

https://waterhouse.ucdavis.edu/whats-in-wine

In [ ]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [ ]:
################################### LOAD THE DATASET ###################################

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
from scipy import stats

# fetch dataset
wine_quality = fetch_ucirepo(id=186)

# data (as pandas dataframes)
df = wine_quality.data.original

################################### EXPORT RAW ###################################

# export raw
df.to_csv("data/00-raw/wine_quality_raw.csv", index=False)

In [ ]:
################################### TIDY THE DATASET ###################################

# first 5 rows
df.head(5)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [ ]:
################################### TIDINESS CONT. & MISSINGNESS ###################################

# variable descriptions
print(wine_quality.variables)

                    name     role         type demographic  \
0          fixed_acidity  Feature   Continuous        None
1       volatile_acidity  Feature   Continuous        None
2            citric_acid  Feature   Continuous        None
3         residual_sugar  Feature   Continuous        None
4              chlorides  Feature   Continuous        None
5    free_sulfur_dioxide  Feature   Continuous        None
6   total_sulfur_dioxide  Feature   Continuous        None
7                density  Feature   Continuous        None
8                     pH  Feature   Continuous        None
9              sulphates  Feature   Continuous        None
10               alcohol  Feature   Continuous        None
11               quality   Target      Integer        None
12                 color    Other  Categorical        None

               description units missing_values
0                     None  None             no
1                     None  None             no
2                     None  None             no
3                     None  None             no
4                     None  None             no
5                     None  None             no
6                     None  None             no
7                     None  None             no
8                     None  None             no
9                     None  None             no
10                    None  None             no
11  score between 0 and 10  None             no
12            red or white  None             no

**TIDINESS:** As seen, each variable forums a column (all variables in `wine_quality.variables` are columns in `df`). Every entry corresponds to one label of wine, and the table is composed of only labels of wine. This satisfies the definition of tidiness, meaning that it is not necessary to further tidy the dataset.

**MISSINGNESS:** By analyzing the second portion of `wine_quality.variables`, we can see that all rows, representing all variables, contain the value `no` for `missing_values`. Therefore, there are no missing data, and there is no missingness to address or impute.

In [ ]:
################################### DATASET SIZE ###################################

# shape prints (rows, columns)
print(df.shape)

(6497, 13)

**SIZE:** `df.shape` returns a clearly visible **6497 rows** and **13 columns**.

In [ ]:
################################### OUTLIERS ###################################

# define z-scores
numeric = df.select_dtypes(include="number").columns.tolist()
z_scores = pd.DataFrame(
    np.abs(stats.zscore(df[numeric])),
    columns=numeric,
    index=df.index,
)

# print % outliers in rows
for col in numeric:
    n = (z_scores[col] > 3).sum()
    print(f"{col:>20s}: {n:5d} outliers ({100 * n / len(df):1.1f}%)")

# flag outliers
df["outlier"] = (z_scores > 3).any(axis=1).map({True: "yes", False: "no"})

       fixed_acidity:   128 outliers (2.0%)
    volatile_acidity:    95 outliers (1.5%)
         citric_acid:    28 outliers (0.4%)
      residual_sugar:    26 outliers (0.4%)
           chlorides:   107 outliers (1.6%)
 free_sulfur_dioxide:    36 outliers (0.6%)
total_sulfur_dioxide:     8 outliers (0.1%)
             density:     3 outliers (0.0%)
                  pH:    33 outliers (0.5%)
           sulphates:    75 outliers (1.2%)
             alcohol:     2 outliers (0.0%)
             quality:    35 outliers (0.5%)
       outlier_count:    63 outliers (1.0%)

In [ ]:
df["outlier"]

0        no
1       yes
2        no
3       yes
4        no
       ...
6492     no
6493     no
6494     no
6495     no
6496     no
Name: outlier, Length: 6497, dtype: object

**OUTLIERS:** We found the percentage of columns in each row of `df` that are more than 3 standard deviations from the mean, printed these values, and then flagged these columns with a new column `df["outlier"]` for potential investigation.

**CLEANLINESS:** As demonstrated in the writeup, all entries in this dataset have strict units and conform to those units. There is no missingness to address, and in the process of checking for outliers it is clear that no data is so wildly deviant from the mean so as to be the wrong datatype or unit, satisfying the definition of cleanliness.

In [ ]:
################################### EXPORT PROCESSED ###################################

# export raw
df.to_csv("data/02-processed/wine_quality.csv", index=False)

## Ethics

<!-- Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/) -->

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?
 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?
 > All wines are sourced from a similar location (Northern Portugal), ensuring that all comparison is relative to wines from a similar origin as all others in the dataset. This means that like is being compared to like: there should be little or no confounding based on the location of collection, etc.
 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?
 > Due to the subjectivity of the 'quality' data column, it is possible that the outcome is biased based on the interests and preferences of those who set that column. We will be clear to outline the relative subjectivity of the study and look for other studies and-or other metrics to compare 'quality' to.

### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
 - [X] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?
 > The dataset already comes with 'quality' pre-rated, and this 'quality' may apply only to the tastes of the specific people who created the dataset. We can do after-studies to compare this 'quality' to potential other rating systems or try to identify discrepancies if there are any.
 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?
 > The 'quality' ratings that we are estimating are subjective, defined by the person who created the dataset. It is possible that their personal tastes may shape the 'quality' column, which is something that can be examined.
 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
 > We will be clear about the region of origin for these data. This is so the model is not interpreted as a general, region-blind model when that is not the case. The model is specific to the region of Portugal for which data are provided in the dataset.
 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?
 > We will need to be clear about how and why we came to our conclusions. This can be done both in our report and through documentation in the code. As the 'quality' ratings are subjective, we will need to be clear in how we relate our findings.

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?
 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
 > It is possible that the metrics suitable for one type of wine may not be suitable for another type. We will keep an eye out for strong in-group trends and consider separating the study into categories or weighing accordingly if a need should arise.
 - [X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 > It is possible that some metrics will prove of relatively little importance to the predictions of our model. In that case, we will need to explain why that is the case, and consider omitting those metrics entirely.
 - [X] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

### E. Deployment
 - [X] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [X] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [X] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?
 > It is possible that this model may be over-generalized by those using it to wine types, locations, and cases that it was not intended to cover and therefore unfairly predict the quality of a wine it wasn't meant to. We plan to be very clear about the origin and intended area of use.

## Team Expectations

Team Expectation #1: We will communicate via groupchat and weekly Zoom meetings.

Team Expectation #2: Should a conflict arise, issues will be handled between the two people. If the conflict effects the entire group, the issue will be brought up within the groupchat for everyone to discuss. If need be, we will meet on Zoom.

Team Expectation #3: We will divide the workload and setup designated due dates, we are each expected to complete our portion of the work on time. If a situation arises where we can't, we will inform the groupchat.

Team Expectation #4: We will work together as a team, have fun, ask questions, and resolve confusion without judgement.

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 2/4  |  5 PM | Brainstorm research questions; Consider datasets that we can use  | Determine meeting dates/times; Fill out research question/hypothesis; Finalize datasets |
| 2/12  |  6 PM |  Look through datasets, review feedback | Assign work, discuss project goals, work on feedback comments |
| 2/17  | 6 PM  | Import and wrangle data  | Review/edit each other's work; assign next assignments   |
| 3/24  | 6 PM  | Continue working on individual work | Review/Edit wrangling/EDA  |
| 3/3  | 6 PM  | Finalize wrangling/EDA; Begin Analysis | Discuss/edit Analysis; Complete project check-in |
| 3/10  | 6 PM  | Complete analysis; Draft results/conclusion/discussion (Wasp)| Discuss/edit full project |
| 3/12  |  6 PM  | Complete assigned work, review whole project, peer review | Go over entire project, finishing touches, turn in final project |